---
- name: Ensure mattermost directory exists
  file:
    path: "{{ stacks_directory }}/mattermost"
    state: directory

- name: Copy Docker Compose template
  template:
    src: docker-compose.yml
    dest: "{{ stacks_directory }}/mattermost/docker-compose.yml"

- name: Deploy Mattermost stack in Docker Swarm
  command: "docker stack deploy --compose-file={{ stacks_directory }}/mattermost/docker-compose.yml mattermost"