---
- name: Create necessary directories for Mattermost
  file:
    path: "./volumes/app/mattermost/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - config
    - data
    - logs
    - plugins
    - client/plugins
    - bleve-indexes

- name: Set ownership for Mattermost directories
  file:
    path: "./volumes/app/mattermost"
    owner: "2000"
    group: "2000"
    state: directory

- name: Ensure mattermost directory exists
  file:
    path: /home/{{ ansible_user }}/mattermost
    state: directory

- name: Copy Docker Compose template
  template:
    src: docker-compose.yml
    dest: /home/{{ ansible_user }}/mattermost/docker-compose.yml

- name: Deploy Mattermost stack in Docker Swarm
  command: docker stack deploy -c /home/{{ ansible_user }}/mattermost/docker-compose.yml mattermost