---
- name: Ensure mattermost directory exists
  file:
    path: "{{ mattermost_directory }}"
    state: directory

- name: Copy Docker Compose template
  template:
    src: docker-stack.yml
    dest: "{{ mattermost_stack_file }}"

- name: Deploy or update Mattermost stack in Docker Swarm
  community.docker.docker_stack:
    name: mattermost
    state: present
    compose:
      - "{{ mattermost_stack_file }}"