---
- name: Ensure mattermost directory exists
  file:
    path: "{{ mm_directory }}"
    state: directory

- name: Ensure Mattermost secrets exist
  community.docker.docker_secret:
    name: "{{ item.name }}"
    data: "{{ item.value }}"
    state: present
  loop:
    - {
      name: mattermost_secret_postgresql_db,
      value: "{{ mm_postgresql_db }}"
    }
    - {
      name: mattermost_secret_postgresql_user,
      value: "{{ mm_postgresql_user }}"
    }
    - {
      name: mattermost_secret_postgresql_password,
      value: "{{ mm_postgresql_password }}"
    }

- name: Copy Docker Compose template
  template:
    src: docker-stack.yml
    dest: "{{ mm_stack_file }}"

- name: Deploy or update Mattermost stack in Docker Swarm
  community.docker.docker_stack:
    name: mattermost
    state: present
    compose:
      - "{{ mm_stack_file }}"