---
# images
service_name: "traefik"
traefik_image: "{{ service_name }}:latest"

# routes
traefik_http_route: "{{ service_name }}.{{ localhost }}"
traefik_https_route: "{{ service_name }}.{{ domain_name }}"

# hosting
domain_owner_mail: "bobniklv@gmail.com"
