---
- name: "Install Docker on all hosts"
  hosts: all
  become: true
  roles:
    - docker

- name: "Setup master host with Docker Swarm"
  hosts: managers
  become: true
  roles:
    - swarm

- name: "Setup workers hosts with Docker Swarm"
  hosts: workers
  become: true
  roles:
    - swarm