---
- name: Initialize Docker Swarm on leader
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ ansible_default_ipv4.address }}"
  register: swarm_init

- name: Retrieve the Swarm Info
  community.docker.docker_swarm_info:
    nodes: true
  register: swarm_info