---
- name: Install Python3 and pip
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Remove old docker-py if it exists
  ansible.builtin.pip:
    name:
      - docker-py
    state: absent

- name: Ensure Docker SDK for Python is installed
  ansible.builtin.pip:
    name:
      - docker
      - jsondiff
    state: present
