- name: Ensure portainer directory exists
  file:
    path: "{{ stacks_directory }}/portainer"
    state: directory

- name: Copy Docker Compose template
  template:
    src: docker-compose.yml
    dest: "{{ stacks_directory }}/portainer/docker-compose.yml"

- name: Deploy Portainer stack
  command: docker stack deploy --compose-file="{{ stacks_directory }}/portainer/docker-compose.yml" portainer