---
- name: Ensure portainer directory exists
  file:
    path: "{{ portainer_directory }}"
    state: directory

- name: Copy Docker Compose template
  template:
    src: docker-stack.yml
    dest: "{{ portainer_stack_file }}"

- name: Deploy or update Portainer stack in Docker Swarm
  community.docker.docker_stack:
    name: portainer
    state: present
    compose:
      - "{{ portainer_stack_file }}"
