---
# general
timezone: "UTC"

# images
mattermost_image: "ghcr.io/yawl-company/yawlmost-image/yawlmost"
postgresql_image: "postgres:13-alpine"
traefik_image: "traefik:latest"

# routes
traefik_http_route: "traefik.localhost"
traefik_https_route: "traefik.yawlco.tech"
mattermost_http_route: "mattermost.localhost"
mattermost_https_route: "mattermost.yawlco.tech"

# hosting
yawl_owner_mail: "bobniklv@gmail.com"
yawl_domain: "yawlco.tech"
