global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true

entryPoints:
  web_insecure:
    address: ":80"
  web_secure:
    address: ":443"

certificatesResolvers:
  cloudflare:
    acme:
      email: "{{ yawl_owner_mail }}"
      storage: /certs/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
        delayBeforeCheck: 60s

providers:
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
