version: '3.8'

networks:
  internal-network:
    driver: overlay
    internal: true
    name: "{{ internal_network_name }}"
  external-network:
    driver: overlay
    internal: false
    name: "{{ external_network_name }}"

volumes:
  mattermost-postgresql:
  mattermost-config:
  mattermost-data:
  mattermost-logs:
  mattermost-plugins:
  mattermost-client-plugins:
  mattermost-bleve-indexes:

secrets:
  mattermost_secret_postgresql_db:
    external: true
  mattermost_secret_postgresql_user:
    external: true
  mattermost_secret_postgresql_password:
    external: true
  cloudflare_dns_api_token:
    external: true

services:
  proxy:
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./:/certs/
    secrets:
      - cloudflare_dns_api_token
    environment:
      TZ: "{{ timezone }}"
      CF_DNS_API_TOKEN_FILE: /run/secrets/cloudflare_dns_api_token
    networks:
      - external-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.proxy == true
      update_config:
        parallelism: 1
        order: start-first
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.network={{ external_network_name }}
        # http
        - traefik.http.routers.traefik.entrypoints=web_insecure
        - traefik.http.routers.traefik.rule=Host(`{{ proxy_route }}`)
        - traefik.http.routers.traefik.service=api@internal
        # core
        - traefik.http.services.traefik.loadbalancer.server.port=8080

  postgres:
    depends_on:
      - proxy
    image: postgres:13-alpine
    volumes:
      - mattermost-postgresql:/var/lib/postgresql/data
    secrets:
      - mattermost_secret_postgresql_db
      - mattermost_secret_postgresql_user
      - mattermost_secret_postgresql_password
    environment:
      TZ: "{{ timezone }}"
      POSTGRES_USER_FILE: /run/secrets/mattermost_secret_postgresql_user
      POSTGRES_PASSWORD_FILE: /run/secrets/mattermost_secret_postgresql_password
      POSTGRES_DB_FILE: /run/secrets/mattermost_secret_postgresql_db
    networks:
      - internal-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.proxy != true
      update_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: on-failure
        max_attempts: 2

  mattermost:
    depends_on:
      - postgres
    image: ghcr.io/yawl-company/yawlmost-image/yawlmost
    volumes:
      - mattermost-config:/mattermost/config
      - mattermost-data:/mattermost/data
      - mattermost-logs:/mattermost/logs
      - mattermost-plugins:/mattermost/plugins
      - mattermost-client-plugins:/mattermost/client/plugins
      - mattermost-bleve-indexes:/mattermost/bleve-indexes
    secrets:
      - mattermost_secret_postgresql_db
      - mattermost_secret_postgresql_user
      - mattermost_secret_postgresql_password
    environment:
      TZ: "{{ timezone }}"
      MM_SQLSETTINGS_DRIVERNAME: "{{ mm_sqlsettings_drivername }}"
      MM_BLEVESETTINGS_INDEXDIR: "{{ mm_blevesettings_indexdir }}"
      MM_SERVICESETTINGS_SITEURL: "{{ mm_servicesettings_siteurl }}"
    networks:
      - internal-network
      - external-network
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.labels.proxy != true
      update_config:
        parallelism: 2
        order: start-first
      restart_policy:
        condition: on-failure
        max_attempts: 2
      labels:
        # core
        - traefik.enable=true
        - traefik.docker.network={{ external_network_name }}
        - traefik.http.services.mattermost.loadbalancer.server.port=8065
        # http
        - traefik.http.routers.mattermost.entrypoints=web_insecure
        - traefik.http.routers.mattermost.rule=Host(`{{ mattermost_http_route }}`)
        # http -> https bridge
        - traefik.http.routers.mattermost.middlewares=https_redirect
        - traefik.http.middlewares.https_redirect.redirectscheme.scheme=https
        # https
        - traefik.http.routers.mattermost-secure.entrypoints=web_secure
        - traefik.http.routers.mattermost-secure.rule=Host(`{{ mattermost_https_route }}`)
        - traefik.http.routers.mattermost-secure.tls=true
        - traefik.http.routers.mattermost-secure.tls.certresolver=cloudflare
        - traefik.http.routers.mattermost-secure.tls.domains[0].main={{ yawl_domain }}
        - traefik.http.routers.mattermost-secure.tls.domains[0].sans=*.{{ yawl_domain }}
