services:
  postgres:
    image: postgres:13-alpine
    volumes:
      - mattermost-postgresql:/var/lib/postgresql/data
    secrets:
      - mattermost_secret_postgresql_db
      - mattermost_secret_postgresql_user
      - mattermost_secret_postgresql_password
    environment:
        TZ: "{{ timezone }}"
        POSTGRES_USER_FILE: /run/secrets/mattermost_secret_postgresql_user
        POSTGRES_PASSWORD_FILE: /run/secrets/mattermost_secret_postgresql_password
        POSTGRES_DB_FILE: /run/secrets/mattermost_secret_postgresql_db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mattermost:
    depends_on:
      - postgres
    image: ghcr.io/this-is-tobi/mirror/mattermost
    ports:
      - "8065:8065"
      - "8443:8443/udp"
      - "8443:8443/tcp"
    volumes:
      - mattermost-config:/mattermost/config
      - mattermost-data:/mattermost/data
      - mattermost-logs:/mattermost/logs
      - mattermost-plugins:/mattermost/plugins
      - mattermost-client-plugins:/mattermost/client/plugins
      - mattermost-bleve-indexes:/mattermost/bleve-indexes
    secrets:
      - mattermost_secret_postgresql_db
      - mattermost_secret_postgresql_user
      - mattermost_secret_postgresql_password
    environment:
        TZ: "{{ timezone }}"
        MM_SQLSETTINGS_DRIVERNAME: "{{ mm_sqlsettings_drivername }}"
        MM_SQLSETTINGS_DATASOURCE: "{{ mm_sqlsettings_datasource }}"
        MM_BLEVESETTINGS_INDEXDIR: "{{ mm_blevesettings_indexdir }}"
        MM_SERVICESETTINGS_SITEURL: "{{ mm_servicesettings_siteurl }}"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

volumes:
  mattermost-postgresql:
  mattermost-config:
  mattermost-data:
  mattermost-logs:
  mattermost-plugins:
  mattermost-client-plugins:
  mattermost-bleve-indexes:

secrets:
  mattermost_secret_postgresql_db:
    external: true
  mattermost_secret_postgresql_user:
    external: true
  mattermost_secret_postgresql_password:
    external: true