global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true

entryPoints:
  web_insecure:
    address: ":80"
  web_secure:
    address: ":443"

certificatesResolvers:
  cloudflare:
    acme:
      email: "yawl.foss@gmail.com"
      storage: /var/traefik/certs/cloudflare-acme.json
      caServer: 'https://acme-staging-v02.api.letsencrypt.org/'
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - 8.8.8.8:53
        delayBeforeCheck: 90

providers:
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
