---
- name: Upgrade all packages to the latest versions
  apt:
    name: '*'
    state: latest
    update_cache: yes

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: "{{ docker_gpg_key_url }}"
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present

- name: Install Docker-CE
  ansible.builtin.apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes